apiVersion: skaffold/v2beta2
kind: Config

build:
  artifacts:
    - image: akervern/dev-base
      context: dev-base
      docker: {}
    - image: akervern/project-base
      context: project-base
      docker: {}
    - image: akervern/code-server-base
      context: code-server-base
      docker: {}
    - image: akervern/project-code-server
      context: project-code-server
      docker: {}
    - image: akervern/theia-builder
      context: theia-builder
      docker: {}
    - image: akervern/theia-base
      context: theia-base
      docker: {}
    - image: akervern/project-theia
      context: project-theia
      docker: {}
test:
  - image: akervern:dev-base
    structureTests:
      - ./tests/base-java.yml
      - ./tests/base-nodejs.yml
  - image: akervern/code-server-base
    structureTests:
      - ./tests/code-server.yml
  - image: akervern/theia-base
    structureTests:
      - ./tests/theia.yml
  - image: akervern/project-code-server
    structureTests:
      - ./tests/base-java.yml
      - ./tests/base-nodejs.yml
      - ./tests/code-server.yml
      - ./tests/code-server-project.yml
  - image: akervern/project-theia
    structureTests:
      - ./tests/base-java.yml
      - ./tests/base-nodejs.yml
      - ./tests/theia.yml
      - ./tests/theia-project.yml

deploy: {}

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      local: { push: false }
      tagPolicy:
        envTemplate:
          template: '{{.IMAGE_NAME}}:latest'
