apiVersion: skaffold/v2beta13
kind: Config

build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: docker.packages.nuxeo.com/nos-dev/dev-base
      context: dev-base
    - image: docker.packages.nuxeo.com/nos-dev/project-base
      context: project-base
    - image: docker.packages.nuxeo.com/nos-dev/shell-project
      context: shell-project
      requires:
        - image: docker.packages.nuxeo.com/nos-dev/dev-base
          alias: DEV_BASE
        - image: docker.packages.nuxeo.com/nos-dev/project-base
          alias: PROJECT_BASE
    - image: docker.packages.nuxeo.com/nos-dev/code-server-base
      context: code-server-base
      requires:
        - image: docker.packages.nuxeo.com/nos-dev/dev-base
          alias: DEV_BASE
    - image: docker.packages.nuxeo.com/nos-dev/code-server-project
      context: code-server-project
      requires:
        - image: docker.packages.nuxeo.com/nos-dev/code-server-base
          alias: CODE_SERVER_BASE
        - image: docker.packages.nuxeo.com/nos-dev/project-base
          alias: PROJECT_BASE
    - image: docker.packages.nuxeo.com/nos-dev/theia-builder
      context: theia-builder
    - image: docker.packages.nuxeo.com/nos-dev/theia-base
      context: theia-base
      requires:
        - image: docker.packages.nuxeo.com/nos-dev/dev-base
          alias: DEV_BASE
        - image: docker.packages.nuxeo.com/nos-dev/theia-builder
          alias: THEIA_BUILDER
    - image: docker.packages.nuxeo.com/nos-dev/theia-project
      context: theia-project
      requires:
        - image: docker.packages.nuxeo.com/nos-dev/theia-base
          alias: THEIA_BASE
        - image: docker.packages.nuxeo.com/nos-dev/project-base
          alias: PROJECT_BASE
    - image: docker.packages.nuxeo.com/nos-dev/bootstrap
      context: bootstrap
      requires:
        - image: docker.packages.nuxeo.com/nos-dev/dev-base
          alias: DEV_BASE
test:
  - image: docker.packages.nuxeo.com/nos-dev/dev-base
    structureTests:
      - ./tests/base-java.yml
      - ./tests/base-nodejs.yml
      - ./tests/base-cloud.yml
      - ./tests/base-nuxeo-tools.yml
  - image: docker.packages.nuxeo.com/nos-dev/project-base
    structureTests:
      - ./tests/base-entrypoints.yml
  - image: docker.packages.nuxeo.com/nos-dev/shell-project
    structureTests:
      - ./tests/base-java.yml
      - ./tests/base-entrypoints.yml
      - ./tests/base-nodejs.yml
      - ./tests/base-cloud.yml
      - ./tests/base-nuxeo-tools.yml
      - ./tests/base-entrypoints.yml
      - ./tests/shell-project.yml
  - image: docker.packages.nuxeo.com/nos-dev/code-server-base
    structureTests:
      - ./tests/code-server.yml
  - image: docker.packages.nuxeo.com/nos-dev/theia-base
    structureTests:
      - ./tests/theia.yml
  - image: docker.packages.nuxeo.com/nos-dev/code-server-project
    structureTests:
      - ./tests/base-java.yml
      - ./tests/base-entrypoints.yml
      - ./tests/base-nodejs.yml
      - ./tests/base-cloud.yml
      - ./tests/base-nuxeo-tools.yml
      - ./tests/base-project.yml
      - ./tests/code-server.yml
      - ./tests/code-server-project.yml
  - image: docker.packages.nuxeo.com/nos-dev/theia-project
    structureTests:
      - ./tests/base-java.yml
      - ./tests/base-entrypoints.yml
      - ./tests/base-nodejs.yml
      - ./tests/base-cloud.yml
      - ./tests/base-nuxeo-tools.yml
      - ./tests/base-project.yml
      - ./tests/theia.yml
      - ./tests/theia-project.yml

deploy: {}

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      local: { push: false }
  - name: jenkins
    activation:
      - env: '!JENKINS_HOME='
    build:
      cluster:
        dockerConfig:
          path: /.skaffold/docker/.dockerconfigjson
        randomPullSecret: true
        randomDockerConfigSecret: true
  - name: branch
    build:
      tagPolicy:
        envTemplate:
          template: '{{.BRANCH_NAME}}'
  - name: release
    build:
      tagPolicy:
        gitCommit: {}
  - name: latest
    build:
      tagPolicy:
        sha256: {}
