apiVersion: skaffold/v2beta2
kind: Config

build:
  artifacts:
    - image: docker.packages.nuxeo.com/nos-dev/dev-base
      context: dev-base
      docker: {}
    - image: docker.packages.nuxeo.com/nos-dev/project-base
      context: project-base
      docker: {}
    - image: docker.packages.nuxeo.com/nos-dev/shell-project
      context: shell-project
      docker: {}
    - image: docker.packages.nuxeo.com/nos-dev/code-server-base
      context: code-server-base
      docker: {}
    - image: docker.packages.nuxeo.com/nos-dev/code-server-project
      context: code-server-project
      docker: {}
    - image: docker.packages.nuxeo.com/nos-dev/theia-builder
      context: theia-builder
      docker: {}
    - image: docker.packages.nuxeo.com/nos-dev/theia-base
      context: theia-base
      docker: {}
    - image: docker.packages.nuxeo.com/nos-dev/theia-project
      context: theia-project
      docker: {}
test:
  - image: docker.packages.nuxeo.com/nos-dev:dev-base
    structureTests:
      - ./tests/base-java.yml
      - ./tests/base-nodejs.yml
      - ./tests/base-cloud.yml
      - ./tests/base-nuxeo-tools.yml
  - image: docker.packages.nuxeo.com/nos-dev:project-base
    structureTests:
      - ./tests/base-entrypoints.yml
  - image: docker.packages.nuxeo.com/nos-dev:shell-project
    structureTests:
      - ./tests/base-java.yml
      - ./tests/base-entrypoints.yml
      - ./tests/base-nodejs.yml
      - ./tests/base-cloud.yml
      - ./tests/base-nuxeo-tools.yml
      - ./tests/base-entrypoints.yml
      - ./tests/shell-project.yml
  - image: docker.packages.nuxeo.com/nos-dev/code-server-base
    structureTests:
      - ./tests/code-server.yml
  - image: docker.packages.nuxeo.com/nos-dev/theia-base
    structureTests:
      - ./tests/theia.yml
  - image: docker.packages.nuxeo.com/nos-dev/code-server-project
    structureTests:
      - ./tests/base-java.yml
      - ./tests/base-entrypoints.yml
      - ./tests/base-nodejs.yml
      - ./tests/base-cloud.yml
      - ./tests/base-nuxeo-tools.yml
      - ./tests/base-project.yml
      - ./tests/code-server.yml
      - ./tests/code-server-project.yml
  - image: docker.packages.nuxeo.com/nos-dev/theia-project
    structureTests:
      - ./tests/base-java.yml
      - ./tests/base-entrypoints.yml
      - ./tests/base-nodejs.yml
      - ./tests/base-cloud.yml
      - ./tests/base-nuxeo-tools.yml
      - ./tests/base-project.yml
      - ./tests/theia.yml
      - ./tests/theia-project.yml

deploy: {}

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      local: { push: false }
      tagPolicy:
        envTemplate:
          template: '{{.IMAGE_NAME}}:latest'
